language: java

jdk:
    - oraclejdk8

services:
    - redis-server
    - mysql
    - mongodb

before_script:
  - mysql -e "create database IF NOT EXISTS kancolle;" -uroot
  - mongoimport -d kancolle -c shop ./mongo_init/shop.dat
  - mongoimport -d kancolle -c stype ./mongo_init/stype.dat

script:
  - mvn test -B -P ci

os:
  - linux