language: java
jdk:
    - oraclejdk8
services:
    - redis-server
    - mysql
    - mongodb
before_install:
  - mysql -e "create database IF NOT EXISTS kancolle;" -uroot
before_script:
  - mongoimport -d kancolle -c shop ./mongo_init/shop.dat