language: java
jdk:
    - oraclejdk8
services:
    - redis-server
    - mysql
    - mongodb
before_script:
  - mysql -e "create database IF NOT EXISTS kancolle;" -uroot
  - mongoimport -d kancolle -c shop ./mongo_init/shop.
script:
  - mvn test -B -Dspring.profiles.active=ci
os:
  - linux