ALTER TABLE `t_ship` CHANGE `YOMI` `YOMI` VARCHAR(255)  CHARACTER SET utf8  COLLATE utf8_general_ci  NOT NULL  DEFAULT ''  COMMENT '名読み';
ALTER TABLE `t_ship` CHANGE `BACKS` `BACKS` TINYINT(4)  UNSIGNED  NOT NULL  COMMENT '稀有度';
ALTER TABLE `t_ship` CHANGE `VOICEF` `VOICEF` TINYINT(4)  UNSIGNED  NOT NULL  COMMENT 'ボイス設定フラグ ビットフラグ';


