UPDATE `kancolle`.`t_slotitem` SET COST = 0 , DISTANCE = 0;

ALTER TABLE `kancolle`.`t_slotitem`
  CHANGE `COST` `COST` TINYINT(3) UNSIGNED NOT NULL,
  CHANGE `DISTANCE` `DISTANCE` TINYINT(3) UNSIGNED NOT NULL;