CREATE TABLE `kancolle`.`t_slotitem_class`(
  `SLOTITEM_CLASS_ID` BIGINT UNSIGNED NOT NULL,
  `NAME` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`SLOTITEM_CLASS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `kancolle`.`t_slotitem_photograph`(
  `SLOTITEM_PHOTOGRAPH_ID` BIGINT UNSIGNED NOT NULL,
  `NAME` VARCHAR(32) NOT NULL,
  `EN_NAME` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`SLOTITEM_PHOTOGRAPH_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `kancolle`.`t_slotitem_categoty`(
  `SLOTITEM_CATEGORY_ID` BIGINT UNSIGNED NOT NULL,
  `NAME` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`SLOTITEM_CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `kancolle`.`t_slotitem_icon`(
  `SLOTITEM_ICON_ID` BIGINT UNSIGNED NOT NULL,
  `NAME` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`SLOTITEM_ICON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;